kind: Deployment
apiVersion: apps/v1
metadata:
  name: molmim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: molmim
  template:
    metadata:
      labels:
        app: molmim
    spec:
      nodeSelector:
        nvidia.com/gpu.deploy.driver: 'true'
      serviceAccountName: molmim
      imagePullSecrets:
        - name: nvcr-io-pull-secret
      containers:
        - name: container
          image: 'nvcr.io/nim/nvidia/molmim:1.0.0'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: NGC_CLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ngc-api-key
                  key: NGC_CLI_API_KEY
      serviceAccount: molmim
